//login
const LOGIN_LOADING = 'LOGIN_LOADING';
const LOGIN_FAIL = 'LOGIN_FAIL';
const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

//taskLog
const LOCATION_DETAIL_INITIALIZING = 'LOCATION_DETAIL_DOWNLOADING';
const LOCATION_DETAIL_INITIALIZING_FAIL = 'LOCATION_DETAIL_DOWNLOADING_FAIL';
const LOCATION_DETAIL_INITIALIZING_SUCCESS = 'LOCATION_DETAIL_DOWNLOADING_SUCCESS';
const ROOM_CLEANED = 'ROOM_CLEANED';
const RESET_ROOM = 'RESET_ROOM';
const LOAD_ROOM = 'LOAD_ROOM';
const EXTRAS_TOGGLE = 'EXTRAS_TOGGLE';

export {
  LOGIN_LOADING,
  LOGIN_FAIL,
  LOGIN_SUCCESS,
  LOCATION_DETAIL_INITIALIZING,
  LOCATION_DETAIL_INITIALIZING_FAIL,
  LOCATION_DETAIL_INITIALIZING_SUCCESS,
  ROOM_CLEANED,
  RESET_ROOM,
  LOAD_ROOM,
  EXTRAS_TOGGLE,
};
